### ISSUE TITLE
An ability to make a combined logger

### ISSUE THREAD

**Issue by dvtomas** [sile/sloggers#8]
I'd like sloggers to be able to configure and instantiate a logger that logs both to `terminal_logger` and `file_logger`.

An example of expected configuration file:

```toml
[terminal_logger]

format = "compact" # full/compact
source_location = "none" # none/module_and_line
timezone = "local" # local/utc
destination = "stdout" # stdout or stderr
level = "info" # trace/debug/info/warning/error/critical

[file_logger]

format = "full" # full/compact
source_location = "none" # none/module_and_line
timezone = "local" # local/utc
level = "info" # debug/info/warning/error/critical
path = "railprofiles.log"
truncate = false # true/false, delete file before
```

Luckily, it is already possible to do it with this code (just stub shown):

```rust
use sloggers::file::FileLoggerConfig;
use sloggers::terminal::TerminalLoggerConfig;

#[derive(Deserialize)]
struct LoggersConfig {
    file_logger: FileLoggerConfig,
    terminal_logger: TerminalLoggerConfig,
}

pub fn logger_from_config_string(config_string: &str) -> Result<Logger, Error> {
    let config: LoggersConfig = toml::from_str(config_string).context("Couldn't parse logger config")?;

    let file_builder = config.file_logger.try_to_builder().context("Couldn't create file log builder from config")?;
    let file_logger = file_builder.build().context("Couldn't build file logger from builder")?;

    let terminal_builder = config.terminal_logger.try_to_builder().context("Couldn't create terminal log builder from config")?;
    let terminal_logger: Logger = terminal_builder.build().context("Couldn't build terminal logger from builder")?;

    let logger = Logger::root(Duplicate::new(file_logger, terminal_logger).fuse(), o!());
    Ok(logger)
}
```

This approach works for me so far, so this is more like a "what if" issue for me.

The interesting questions are

 - should this be part of sloggers?
 - does this approach scale? That said, I must mention that I like the approach of [slog-config](https://crates.io/crates/slog-config), where an arbitrary number of drain factories can be registered and used to process the configuration. Maybe sloggers could benefit from this approach sometime in the future as well...
