### ISSUE TITLE
Add support for slog_kvfilter

### ISSUE THREAD

**Issue by dvtomas** [sile/sloggers#9]
Add support to have different logging levels based on [slog_kvfilter](https://docs.rs/slog-kvfilter/0.4.0/slog_kvfilter/) for both `terminal_logger` and `file_logger`.

The configuration could look e.g. something like

```toml

type = "terminal" # terminal or file
format = "full" # full or compact
source_location = "module_and_line" # none or module_and_line
timezone = "utc" # utc or local
level = "info" # one of trace, debug, info, warning, error, critical
destination = "stderr" # stderr or stdout

[[kv_filter]]
key="http_server"
values = ["get", "post"]
level="debug"

[[kv_filter]]
key="hw-subsystem"
values = ["camera"]
level="debug"
```

This would mean dragging in `slog_kvfilter` as a crate dependency. If not desired, perhaps it could be done as an optional feature.

**Comment by sile** [comment]
Since `kv_filter` is a lightweight crate, I think adding it to dependencies has no problem.

**Comment by sile** [comment]
According to the convention of `sloggers`, it may be better to specify the filter configuration as follows:

```toml
[[filter]]
type = "kv"  # Designates the type of this filter using "type" field
key="http_server"
values = ["get", "post"]
level="debug"

[[filter]]
type = "kv"
key="hw-subsystem"
values = ["camera"]
level="debug"
```
